export const FARM_TYPES = [
  "Livestock",
  "Crops",
  "Poultry",
  "Dairy",
  "Organic",
  "Apiculture",
];

export const NIGERIAN_STATES = [
  "Lagos",
  "Kano",
  "Oyo",
  "Rivers",
  "Kaduna",
  "Ogun",
  "Enugu",
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Gombe",
  "Imo",
  "Jigawa",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Nasarawa",
  "Niger",
  "Ondo",
  "Osun",
  "Plateau",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
  "FCT",
];

export const DAYS_OF_WEEK = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];

// lib/constants.ts

export const PRODUCE_CATEGORIES = [
  "Livestock",
  "Crops",
  "Poultry",
  "Dairy",
  "Organic",
  "Apiculture",
] as const;

export const UNITS_BY_CATEGORY: Record<string, string[]> = {
  Livestock: ["heads", "kg"],
  Crops: ["kg", "bags", "baskets", "tons", "tubers"],
  Poultry: ["heads", "kg", "crates"],
  Dairy: ["liters", "bottles", "gallons"],
  Organic: ["kg", "bags", "bundles"],
  Apiculture: ["kg", "jars", "liters"],
};

export const produceMap: Record<string, string> = {
  // --- STAPLES & GRAINS ---
  maluu: "cow",
  ehi: "cow",
  saniya: "cow",
  nama: "cow",
  iresi: "rice",
  osikapa: "rice",
  shinkafa: "rice",
  ewa: "beans",
  agwa: "beans",
  wake: "beans",
  agbado: "maize",
  oka: "maize",
  masara: "maize",
  gari: "garri",
  lebu: "garri",

  // --- TUBERS ---
  isu: "yam",
  ji: "yam",
  doya: "yam",
  paki: "cassava",
  akpu: "cassava",
  rogo: "cassava",
  anamo: "potato",
  "ji nunu": "potato",
  dankali: "potato",

  // --- VEGETABLES & SPICES ---
  ata: "pepper",
  ose: "pepper",
  barkono: "pepper",
  alubosa: "onion",
  yabasi: "onion",
  albasa: "onion",
  tomati: "tomato",
  tumatur: "tomato",
  atale: "ginger",
  jinja: "ginger",
  citta: "ginger",
  ila: "okra",
  okwuru: "okra",
  kubewa: "okra",
  ewuro: "bitter leaf",
  onugbu: "bitter leaf",
  shuwaka: "bitter leaf",

  // --- PROTEINS ---
  eyin: "egg",
  // okuko: "egg" || "chicken",
  okuko: "egg",
  kwai: "egg",
  adiye: "chicken",
  // okuko: "chicken",
  kaza: "chicken",
  ewure: "goat",
  ewu: "goat",
  akuya: "goat",
  ayuu: "garlic",
};
